# 工作流的名称
name: LotteryResult

# 工作流运行的名称
run-name: ${{ github.workflow }} ${{ github.sha }}

# 指定此工作流的触发器
on:
  schedule:
    - cron: "*/1 * * * *" # 每1分钟自动执行一次
  workflow_dispatch: # 可以手动执行

jobs:
  # 检查成绩
  LotteryResult:
    name: LotteryResult

    # 在最新版的Ubuntu系统上运行
    runs-on: ubuntu-latest

    steps:
      # 使用GitHub Actions提供的动作来检出代码库
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Configure Git
        run: |
          # 配置Git用户信息
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # 配置Python环境
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "*"

      - name: Install dependencies
        run: |
          # 使用pip安装项目的依赖项
          pip install requests opencc pytz

      - name: Get Connection
        run: |
          # 获取连接信息
          url="https://ifconfig.me/all"
          response=$(curl -s -X GET "$url")
          echo "$response"

      - name: Run main program
        id: run_main_program
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          GITHUB_ACTIONS: ${{github.actions}}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_ACTOR_ID: ${{ github.actor_id }}
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          REPOSITORY_NAME: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          # 运行主程序
          export BEIJING_TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')"
          echo "BEIJING_TIME=$BEIJING_TIME" >> $GITHUB_OUTPUT
          python main.py
          echo "------"

          # 方便通过截图快速定位到用户
          echo "Branch Name: $GITHUB_REF_NAME"
          echo "Triggered By: $GITHUB_EVENT_NAME"
          echo "Initial Run By: $GITHUB_ACTOR"
          echo "Initial Run By ID: $GITHUB_ACTOR_ID"
          echo "Initiated Run By: $GITHUB_TRIGGERING_ACTOR"
          echo "Repository Name: $REPOSITORY_NAME"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Workflow Name: $GITHUB_WORKFLOW"
          echo "Workflow Number: $GITHUB_RUN_NUMBER"
          echo "Workflow ID: $GITHUB_RUN_ID"
          echo "Beijing Time: $BEIJING_TIME"
          echo "Copyright © 2024 NianBroken. All rights reserved."
          echo "Author's website: https://www.nianbroken.top/"
          echo "Author's Repository URL: https://github.com/NianBroken/ZFCheckScores/"

      - name: Delete __pycache__ folder
        run: |
          # 删除__pycache__文件夹
          rm -rf __pycache__
          rm -rf scripts/__pycache__

      - name: Force push changes to main branch
        run: |
          # 将更改强制推送到main分支
          git add .
          git commit -m "Update from GitHub Actions" || true
          git push origin main --force